services:
  db:
    image: mysql:8.0
    container_name: books_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: books_store_db
      MYSQL_USER: bookuser
      MYSQL_PASSWORD: bookpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build: .
    container_name: books_app
    ports:
      - "80:3000"
    environment:
      - PORT=3000
      - DB_HOST=db
      - DB_USER=bookuser
      - DB_PASSWORD=bookpassword
      - DB_NAME=books_store_db
      - DB_PORT=3306
    depends_on:
      - db

volumes:
  mysql_data:
